// <auto-generated />
using System;
using EmployeeCompany.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeCompany.DB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210706135245_CompanySeed")]
    partial class CompanySeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("EmployeeCompany.Model.Company", b =>
                {
                    b.Property<string>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("uuid");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edited_at");

                    b.Property<string>("EditedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("edited_by");

                    b.HasKey("UUID");

                    b.ToTable("tbl_company");

                    b.HasData(
                        new
                        {
                            UUID = "13ad310c-d2bd-4c77-a9d4-5a4a9bb2323c",
                            CompanyName = "MilliPixel",
                            CreatedAt = new DateTime(2020, 12, 17, 16, 54, 37, 199, DateTimeKind.Local).AddTicks(578),
                            CreatedBy = "migration"
                        });
                });

            modelBuilder.Entity("EmployeeCompany.Model.Employee", b =>
                {
                    b.Property<string>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("uuid");

                    b.Property<string>("Comp_Id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comp_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edited_at");

                    b.Property<string>("EditedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("edited_by");

                    b.Property<string>("EmpName")
                        .HasColumnType("longtext");

                    b.HasKey("UUID");

                    b.HasIndex("Comp_Id");

                    b.ToTable("tbl_employee");
                });

            modelBuilder.Entity("EmployeeCompany.Model.Employee", b =>
                {
                    b.HasOne("EmployeeCompany.Model.Company", "CompanyMapping")
                        .WithMany()
                        .HasForeignKey("Comp_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
